# Generated by Django 2.2.1 on 2019-06-14 06:44

from django.db import migrations, models
import rest_framework.authentication


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_auto_20190611_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BearerAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(rest_framework.authentication.TokenAuthentication, models.Model),
        ),
    ]
